{application,termbox2_nif,
             [{description,"Underlying NIF to use the termbox2 C API"},
              {vsn,"0.1.5"},
              {pkg_name,termbox2_nif},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[termbox2,termbox2_nif]},
              {licenses,["Apache-2.0"]},
              {links,[{"GitHub",
                       "https://github.com/Hydepwns/termbox2-nif"}]}]}.
