name = "termbox2_gleam"
version = "2.0.0"

description = "Gleam wrapper for the termbox2_nif NIF library, providing terminal UI capabilities via termbox2."
licences = ["MIT"]

repository = { type = "github", user = "Hydepwns", repo = "termbox2-nif" }
links = [{ title = "Website", href = "https://github.com/Hydepwns/termbox2-nif" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 0.23.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
